### ISSUE TITLE
[cvmc] Outdated source code without developer branch is causing CIs to fail.

### ISSUE THREAD

**Issue by yellows111** [Cosmic-Sans/collab-vm-web-app#9]
I cant paste this in collab-vm-server nor collab-vm-common so im just putting it here, but it seems collab-vm-common is outdated to the current server/dev branch, suggesting you set up a developer branch or commit directly to collab-vm-common to stop a dependancy problem with building and also CI building.

**Comment by CHOCOLATEMAN69** [comment]
lol fixed
